### ISSUE TITLE
Poné en privado los acertijos de intro

### ISSUE THREAD

**Issue by jos-cab** [ElPalme08/TP-Regex-Bash#1]
Tenés el código de los acertijos públicos
Cualquiera se puede copiar de vos

**Comment by martinkupa** [comment]
a casa me copie todo riiiip /s

**Comment by martinkupa** [comment]
> Tenés el código de los acertijos públicos Cualquiera se puede copiar de vos

Es este repo no, el que forkeaste de los tests
